### ISSUE TITLE
I run train.py on windows and the following error occurs. Will this version of the code work on Windows? thank you very much!

### ISSUE THREAD

**Issue by Liaoxianwen** [pitrack/arglinking#8]
Traceback (most recent call last):
  File "D:/PyProj_Pytorch/RAMS/arglinking-master/miso/commands/train.py", line 10, in <module>
    from miso import models as Models
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\models\__init__.py", line 1, in <module>
    from .model import Model
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\models\model.py", line 19, in <module>
    from miso.data.dataset import Batch
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\__init__.py", line 1, in <module>
    from miso.data.dataset_readers.dataset_reader import DatasetReader
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\dataset_readers\__init__.py", line 10, in <module>
    from miso.data.dataset_readers.dataset_reader import DatasetReader
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\dataset_readers\dataset_reader.py", line 4, in <module>
    from miso.data.instance import Instance
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\instance.py", line 3, in <module>
    from miso.data.fields.field import DataArray, Field
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\fields\__init__.py", line 7, in <module>
    from miso.data.fields.index_field import IndexField
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\fields\index_field.py", line 11, in <module>
    class IndexField(Field[torch.Tensor]):
  File "D:\PyProj_Pytorch\RAMS\arglinking-master\miso\data\fields\index_field.py", line 48, in IndexField
    @overrides
  File "D:\programfile\Anaconda3\envs\RAMS\lib\site-packages\overrides\overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "D:\programfile\Anaconda3\envs\RAMS\lib\site-packages\overrides\overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "D:\programfile\Anaconda3\envs\RAMS\lib\site-packages\overrides\overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "D:\programfile\Anaconda3\envs\RAMS\lib\site-packages\overrides\signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "D:\programfile\Anaconda3\envs\RAMS\lib\site-packages\overrides\signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: IndexField.empty_field: return type `None` is not a `miso.data.fields.field.Field`.

Process finished with exit code 1

**Comment by pitrack** [comment]
It's not clear whether this is related to windows specifically (we developed, trained, etc all on linux), or whether something is incorrect with how you're calling the code and what your input/output is?

Could you provide more information?

Thanks!

**Comment by nurakib** [comment]
I am also facing the same issue. Did you able to figure it out?
